server:
  port: 18080

spring:
  application:
    name: customer

  # Note; this datasource; will connect to the docker image; via localhost port mapping
  datasource:
    password: password
#    url: jdbc:postgresql://localhost:15432/customer
    url: jdbc:postgresql://postgres:15432/customer
    username: ismail
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  zipkin:
#    base-url: http://localhost:9411
    base-url: http://zipkin:9411

  rabbitmq:
    addresses: rabbitmq:5672
#    addresses: localhost:5672


eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true