# This is a docker composition; needs to be execution from command line
# see: https://docs.docker.com/compose/
# command to run:
# docker compose up -d
#

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ismail
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    # we need to use 15432 to avoid clashing wiht postgres db on localhost
    ports:
      - "15432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped




  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
#    networks:
#      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"         # clients will be connecting to this one
      - "15672:15672"       # management port

#    networks:
#      - spring
  #  eureka-server:
  #    image: amigoscode/eureka-server:latest
  #    container_name: eureka-server
  #    ports:
  #      - "8761:8761"
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=docker
  #    networks:
  #      - spring
  #    depends_on:
  #      - zipkin
  #  apigw:
  #    image: amigoscode/apigw:latest
  #    container_name: apigw
  #    ports:
  #      - "8083:8083"
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=docker
  #    networks:
  #      - spring
  #    depends_on:
  #      - zipkin
  #      - eureka-server
#  customer:
#    image: ismailfer/customer:latest
#    container_name: customer
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#      - postgres
#    depends_on:
#      - zipkin
#      - postgres
#      - rabbitmq
#  fraud:
#    image: ismailfer/fraud:latest
#    container_name: fraud
#    ports:
#      - "8081:8081"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#      - postgres
#    depends_on:
#      - zipkin
#      - postgres
#      - rabbitmq
#  notification:
#    image: ismailfer/notification:latest
#    container_name: notification
#    ports:
#      - "8082:8082"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#      - postgres
#    depends_on:
#     - zipkin
#      - postgres
#      - rabbitmq


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: