spring:
  application:
    name: eureka

  zipkin:
#    base-url: http://localhost:9411
    base-url: http://zipkin:9411

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

